//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayer.Pegasus.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bayer.Pegasus.Utils.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  e .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve estar entre .
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  caracteres.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deve ser maior que.
        /// </summary>
        public static string MustBeBiggerThan {
            get {
                return ResourceManager.GetString("MustBeBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser preenchido..
        /// </summary>
        public static string MustBeFilled {
            get {
                return ResourceManager.GetString("MustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um CNPJ válido..
        /// </summary>
        public static string MustBeValidCNPJ {
            get {
                return ResourceManager.GetString("MustBeValidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um CPF válido..
        /// </summary>
        public static string MustBeValidCPF {
            get {
                return ResourceManager.GetString("MustBeValidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser uma data válida no formato (dd/mm/aaaa)..
        /// </summary>
        public static string MustBeValidDate {
            get {
                return ResourceManager.GetString("MustBeValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um valor decimal válido..
        /// </summary>
        public static string MustBeValidDecimalValue {
            get {
                return ResourceManager.GetString("MustBeValidDecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um e-mail válido..
        /// </summary>
        public static string MustBeValidEmail {
            get {
                return ResourceManager.GetString("MustBeValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um inteiro válido..
        /// </summary>
        public static string MustBeValidIntegerValue {
            get {
                return ResourceManager.GetString("MustBeValidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um telefone válido..
        /// </summary>
        public static string MustBeValidPhoneNumber {
            get {
                return ResourceManager.GetString("MustBeValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser uma data válida no formato (hh:mm)..
        /// </summary>
        public static string MustBeValidTime {
            get {
                return ResourceManager.GetString("MustBeValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deve ser um CEP válido..
        /// </summary>
        public static string MustBeValidZipCode {
            get {
                return ResourceManager.GetString("MustBeValidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo .
        /// </summary>
        public static string TheField {
            get {
                return ResourceManager.GetString("TheField", resourceCulture);
            }
        }
    }
}
